openapi: 3.0.0
info:
  title: Books API
  version: 1.0.0
servers:
  - url: https://example.com
tags:
  - name: Books
    description: Operations related to books
security:
    - JWT:
      - write
paths:
  /auth:
    $ref: 'paths/auth.yaml'
  /books:
    get:
      summary: Get a list of books
      operationId: getBooks
      tags:
        - Books
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookList'
        '400':
          description: Bad Request - Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message indicating invalid input
                    example: Invalid input data
    post:
      summary: Add a new book
      operationId: addBook
      tags:
        - Books
      security:
        - JWT: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookRequest'
      responses:
        '201':
          description: Book successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookResponse'
        '400':
          description: Bad Request - Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message indicating invalid input
                    example: Invalid input data
components:
  schemas:
    BookRequest:
      type: object
      properties:
        title:
          type: string
          description: The title of the book
          example: "To Kill a Mockingbird"
        author:
          type: string
          description: The author of the book
          example: "Harper Lee"
        publishedYear:
          type: integer
          description: The year the book was published
          example: 1960
      required:
        - title
        - author
        - publishedYear

    BookResponse:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier for the newly added book
          example: 2
        title:
          type: string
          description: The title of the book
          example: "To Kill a Mockingbird"
        author:
          type: string
          description: The author of the book
          example: "Harper Lee"
        publishedYear:
          type: integer
          description: The year the book was published
          example: 1960

    BookList:
      type: array
      items:
        $ref: '#/components/schemas/BookResponse'

  securitySchemes:
    JWT:
      type: http
      scheme: bearer
